spring:
  jpa:
    show-sql: true

#logging.level.org.hibernate: TRACE

spring.datasource:
  platform: org.hibernate.dialect.MySQL5InnoDBDialect
  url: jdbc:mysql://localhost:3306/datafeed?verifyservercertificate=false&useSSL=false&requireSSL=false&autoReconnect=true
  username: datafeed
  password: datafeed
  tomcat:
    max-idle: 2
    max-active: 2
    time-between-eviction-runs-millis: 5000
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true

oiritaly.datasource:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/datafeed?verifyservercertificate=false&useSSL=false&requireSSL=false&autoReconnect=true
  username: datafeed
  password: datafeed
  max-idle: 2
  max-active: 2
  time-between-eviction-runs-millis: 5000
  test-on-borrow: true
  validation-query: SELECT 1
  test-while-idle: true