spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  datasource:
    platform: h2
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2.console.enabled: true

  batch.initializer.enabled: true

scheduling.quartz:
  database-init-script: data-feed-batch-api/sql/quartz/tables_h2.sql

oiritaly.datasource:
  platform: h2
  url: jdbc:h2:mem:oir;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:
  dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    #root: debug
    #org.springframework.boot.autoconfigure.logging: debug
