INSERT INTO datafeed.Brand (`_id`, name) VALUES (2,'Citizen');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (3,'Agios');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (4,'Breil');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (5,'Morellato');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (6,'Bliss');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (7,'Comete');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (8,'Adami & Martucci');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (10,'Artigianale');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (11,'Acca');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (12,'21punto9');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (13,'Alfieri & St. john');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (14,'Antica Murrina Venezia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (16,'Alviero Martini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (17,'Antora-');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (18,'Ambrosia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (19,'Amore & Baci');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (20,'Annamaria Cammilli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (21,'Aquaforte');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (22,'Arcadia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (23,'Argenesi Argenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (24,'Arkano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (25,'Artecora');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (26,'Artenigma');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (27,'Artlinea');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (28,'Athena');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (29,'Baraka');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (30,'Barrett');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (31,'Baume & Mercier');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (32,'Berry Logan');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (33,'Betta G');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (34,'Bibigi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (35,'Bicchielli e Pasquini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (36,'Bluamante');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (37,'Boccadamo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (38,'Bolcas');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (39,'Breil Tribe');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (40,'Brera');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (41,'Brosway');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (42,'Bucintoro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (43,'Bulova');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (44,'Burberry');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (45,'Calvin Klein');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (46,'Campagnolo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (47,'Candino');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (48,'Capital');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (49,'Carlo Pignatelli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (50,'Cartapietra');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (51,'Casio');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (52,'Cassetti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (53,'Cesare Paciotti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (54,'Chimento');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (55,'Christian Dior');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (56,'Chronostar');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (57,'Chronotech');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (58,'Claudio Fiorentino');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (59,'Converse');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (60,'CP gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (61,'Cupillard Rieme');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (62,'D&G');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (63,'Dalla Bona');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (64,'Damiani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (65,'Davite & Delucchi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (66,'Dea Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (67,'Delta');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (68,'Demetra');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (69,'Diadema');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (70,'Diesel');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (71,'Diodoro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (72,'DKNY');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (73,'Donna Oro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (74,'Eberhard');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (75,'Eclat');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (76,'Emporio Armani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (77,'Enrico Coveri');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (78,'Facco');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (79,'Ferrari Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (80,'Scuderia Ferrari');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (81,'Festina');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (82,'FifthAvenue');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (83,'Fiorini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (84,'First Class');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (85,'Fope');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (86,'Fraboso');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (87,'Frederique Constant');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (88,'G.M.D. Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (89,'Gabor');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (90,'Gagà');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (91,'Gai Mattiolo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (92,'Gala');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (93,'Garmin');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (94,'Gattinoni');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (95,'Genesia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (96,'Gibi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (97,'Giorgio Visconti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (98,'Gold & Silver Line');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (99,'Graziella');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (100,'Greggio');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (101,'Gucci');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (102,'Guess');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (103,'Hamilton');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (104,'Haurex');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (105,'Hellas');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (106,'Hello kitty');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (107,'Hip Hop');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (108,'I Gioielli di Alessia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (109,'Ice Watch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (110,'Imperial');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (111,'In Deum');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (112,'Invicta');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (113,'Ippocampo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (114,'Jack&co');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (115,'Jean Paul');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (116,'Just a minute');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (117,'Just Cavalli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (118,'K&Bros');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (119,'Kenneth Cole');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (120,'Kiara');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (121,'Lacoste');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (122,'Locman');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (295,'Alpina');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (123,'Longines');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (124,'Lorenz');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (125,'Lorenzo Ungari');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (126,'Lotus');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (127,'Louis Erard');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (128,'Zzero');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (129,'Ziel');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (130,'Zenith');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (131,'Zancan');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (132,'Yukiko');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (133,'Yukey');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (134,'Wyler Vetta');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (135,'World Diamond Group');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (136,'Victorinox');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (137,'Vetta');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (138,'Veneroso');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (139,'Valenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (140,'Vai Milano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (141,'Vagary');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (142,'Unoaerre');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (143,'Unode50');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (144,'U.S. Polo Assn');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (145,'Tuum');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (146,'Tryò');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (147,'Trudi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (148,'Tissot');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (149,'Timex');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (150,'Ti Sento Milano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (151,'Thilia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (152,'Theorein Kelek');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (153,'Theorein');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (154,'Terra Cielo Mare');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (155,'Tedora');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (156,'Tag Heuer');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (157,'Swatch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (158,'Suunto');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (159,'Superoro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (160,'Sun Day');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (161,'Stroili Oro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (162,'Staurino');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (163,'Speedometer Official');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (164,'Sovrani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (165,'SmileSolar');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (166,'Silvia Kelly');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (167,'Lowell');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (168,'Lucien Rochat');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (169,'Lucos');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (170,'Luisa Della Salda');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (171,'Luxoro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (172,'Madness Milano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (173,'Magie Preziose');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (174,'Marcello Giorgio');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (175,'Marco Mavilla');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (176,'Maria Cristina Sterling');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (177,'Maserati');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (178,'Masini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (179,'Maurice Lacroix');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (180,'Memphis Belle');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (181,'Menegatti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (182,'Mikimoto');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (183,'Miluna');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (184,'Misaki');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (185,'Miss Sixty');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (186,'Molecole');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (187,'Mondia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (188,'Monile');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (189,'Morini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (190,'Moschino');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (191,'Moviestone');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (192,'Nanis');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (194,'Neonero');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (193,'Nautica');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (195,'New Planet');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (196,'Nimei');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (197,'Nomination');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (198,'Novello Preziosi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (199,'Nuovegioie');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (200,'Officina Bernardi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (201,'Omega');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (202,'Ops!');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (203,'Oregon Scientific');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (204,'Osa Jewels');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (205,'Ottaviani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (206,'Paul Picot');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (207,'Perseo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (208,'Philip Watch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (209,'Philippe Starck (S+ARCH)');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (210,'Pianegonda');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (211,'Piero Milano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (212,'Pierre Bonnet');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (213,'Pierre Cardin');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (214,'Pinko');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (215,'Pirelli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (216,'Polar');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (217,'Police');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (218,'Ponte Vecchio Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (219,'Pryngeps');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (220,'Pulsar');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (221,'Rado');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (222,'Raima');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (223,'Rampini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (224,'Raspini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (225,'Raymond Weil');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (226,'Rebecca');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (227,'Recarlo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (228,'Renato Balestra');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (229,'Rhythm');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (230,'Roberto Cavalli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (231,'Roberto Demeglio');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (232,'Roberto Giannotti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (233,'Rolex');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (234,'Rosato');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (235,'Rosso Amante');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (236,'Sacchetti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (237,'Salvini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (238,'Savoia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (239,'Segni Preziosi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (240,'Seiko');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (241,'Sequenze Argenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (242,'Sheffield');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (243,'Shiné');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (244,'Noblia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (247,'Laura Biagiotti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (248,'Laura Bellini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (249,'Laurens');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (250,'Leaderline');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (251,'Le Bebé');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (252,'Levi\'s Strauss');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (253,'Light Time');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (254,'Liu Jo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (255,'2Jewels');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (256,'Fossil');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (257,'Sector');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (258,'Zoppini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (259,'Hoops');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (265,'Venini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (266,'Skagen');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (9,'Unbranded');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (261,'Polello');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (262,'Afrodite');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (263,'Zoccai');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (264,'Mooby');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (267,'Michael Kors');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (268,'Mabina');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (270,'Mymara');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (271,'Vezzaro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (272,'4US: Cesare Paciotti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (273,'Seguso Viro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (274,'Buccellati');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (275,'Daniel Wellington');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (276,'Cartier');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (277,'Quagliotto');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (278,'Revue');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (279,'Emile Pequignet');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (280,'Ducati');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (281,'Casa Reale');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (282,'Ebel');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (283,'Franco Giuntini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (284,'La Croisette');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (285,'Hermes');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (286,'Kienzle');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (287,'Amen');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (288,'Ingersoll');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (289,'Breitling');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (290,'Perregaux');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (291,'Blumarine');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (292,'Winchester');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (293,'Eterna');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (294,'DLight Jewels');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (296,'Borsari gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (297,'Disney');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (298,'SoloTuo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (299,'T-Watch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (390,'Eilat');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (304,'André Le Marquand');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (356,'Venezia 333');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (337,'Mikiko');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (300,'Versus Vesace');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (301,'Engelsrufer');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (302,'Heuer');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (303,'Ab Aeterno');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (332,'Massimo Raiteri');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (333,'Buzio Luciano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (334,'Momo Design');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (335,'Kris');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (305,'Chini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (306,'Montblanc');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (307,'Marco Bicego');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (308,'Misani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (309,'Mimi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (310,'Mattioli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (311,'Etnò');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (312,'Talento Italiano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (313,'Fibo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (314,'Bronzallure');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (315,'Venerio');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (316,'IWC');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (317,'Altanus');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (318,'Julie Julsen');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (319,'Rubinia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (320,'Diva Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (321,'Kidult');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (323,'Braccialini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (324,'Tamashii');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (325,'Marakò');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (326,'Autologico');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (327,'Muhle Glashutte');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (328,'Manega Orologi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (329,'Dogale');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (330,'Petralux');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (331,'Alessandro Testi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (339,'Federica Rossi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (340,'Dal Fior Mario');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (341,'Franck Muller');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (342,'Bugatti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (343,'Officina del tempo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (345,'Nouvelle Bague');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (344,'Spazio24');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (346,'Ultima Edizione');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (347,'Fani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (348,'Levrette');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (349,'Montres De Luxe');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (350,'Fahrenheit');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (351,'Misis');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (352,'Fonten');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (353,'Andrea Piccini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (354,'Carini Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (355,'Swarovski');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (359,'Toy Watch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (360,'Ziio');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (362,'Rue des Mille');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (363,'Henry London');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (364,'Wewood');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (365,'Air Watch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (366,'Bering');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (367,'Timberland');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (368,'Cameo Italiano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (371,'Adidas');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (370,'Movado');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (372,'J-Jo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (374,'Fidia Firenze');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (375,'Colonna');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (376,'Saturno');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (377,'Navigare');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (378,'Gemmarium');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (379,'Stile Prezioso');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (380,'GiòYellou');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (381,'Santomà');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (383,'Piquadro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (384,'Iesus');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (385,'Glam Rock');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (386,'Gabriella Rivalta');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (387,'MeisterSinger');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (389,'Humilis');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (391,'Pesavento');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (392,'Mia Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (393,'Chantecler');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (394,'Wintex');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (395,'Leo Pizzo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (396,'Junghans');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (397,'Tous');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (398,'Igi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (399,'TouchMe!');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (400,'GreenTime');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (401,'UrbanStyle');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (402,'La Gatta Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (403,'Caramella');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (404,'Ciclon');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (405,'Anteo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (406,'My Ring');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (407,'Calypso');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (408,'Italsilver - ITS');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (409,'Lorus');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (410,'Marlù');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (411,'Mida Argenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (412,'Emotiva by Fiorini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (413,'Rajola');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (414,'Coscia Perle');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (415,'Crivelli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (416,'Lenti & Villasco');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (417,'Giadan');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (418,'UomOro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (421,'Ardé');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (420,'Valori');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (422,'Gielle');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (423,'Cluse Watches');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (424,'Estego');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (425,'Rodania');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (426,'Jaeger LeCoultre');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (427,'Gemoro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (428,'Luca Lorenzini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (429,'Mirco Visconti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (430,'Aeronautica Militare');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (513,'Maman et Sophie');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (431,'Frecce Tricolori');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (432,'Paris Hilton');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (433,'Mode');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (434,'Herzengel');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (435,'Graham');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (436,'Scanavin');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (437,'Dietrich');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (438,'QLOCKTWO');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (439,'Mondaine');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (440,'Corum');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (441,'U-Boat');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (442,'Jacob & Co.');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (443,'Meccaniche Veloci');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (444,'Cyma');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (445,'Aragonesi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (446,'Byblos');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (447,'Miss Miss');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (448,'Salvatore Arzani');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (449,'2R Argenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (450,'Camilletti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (451,'De Marco Argenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (452,'Smarty');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (453,'Sweet Years');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (454,'Flik Flak');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (455,'Yvone Christa');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (456,'Thomas Sabo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (457,'Sixties');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (458,'Lotto');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (459,'Bagutta');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (460,'Zitto');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (461,'Napkin');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (462,'Ink for Vasco');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (463,'Silverbone');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (464,'Spadarella');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (465,'Hook');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (466,'Waldmann');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (468,'Fiorucci');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (469,'AVI-8');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (470,'Dog Fever');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (471,'Cerruti 1881');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (472,'Manuel Zed');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (473,'Agir Watch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (474,'CuorePuro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (475,'Queriot');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (476,'Orsini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (477,'Antonella Piacenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (478,'Certina');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (479,'Kurshuni');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (480,'Cesa 1882');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (481,'Ricci Argenti');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (482,'Jeanrichard');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (483,'ti sento');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (484,'Il Centimetro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (485,'Kenzo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (486,'Keep Me');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (487,'Pepe Jeans');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (488,'My Jewels');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (489,'Ink');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (490,'Together');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (491,'Pandora');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (492,'Vanesia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (493,'La Brune et La Blonde');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (494,'Tom Hope');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (495,'Yonger & Bresson');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (497,'Marco Gerbella');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (498,'Furla');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (499,'Roamer');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (503,'Fortis');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (501,'Daniela De Marchi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (502,'Laurent Gandini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (504,'Dada Arrigoni');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (505,'Kulto');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (506,'We Positive');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (507,'Pearl Bracelets');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (508,'Protagonista');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (509,'Briston');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (510,'Giuli Jewels');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (511,'Techmade');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (512,'Harry Williams');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (514,'Vintage');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (515,'Mediterraneo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (516,'Chrysalis');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (517,'Krizia');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (518,'Rifle');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (519,'Trazo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (520,'APM Monaco');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (521,'Ayala Bar');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (522,'Centopercentocachemire');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (523,'Sacramore Firenze');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (524,'Alcozer & J');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (525,'Radius');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (526,'Rosso Design');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (527,'Reporter');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (528,'Details');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (529,'Nike');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (530,'Anonimo Firenze');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (531,'Scatola del Tempo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (532,'Lenval');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (533,'Nautische Instrumente Mühle-Glashütte');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (534,'Luca Barra');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (535,'Idandi');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (536,'Pomellato');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (537,'Dodo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (538,'Segnamore');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (540,'Kamawatch');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (542,'Giollaro');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (543,'Tommy Hilfiger');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (544,'Arte Del Tempo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (545,'D1 Milano');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (554,'L\'Ura Lumbarda');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (551,'Tatù');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (550,'BPEMR');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (552,'Huawei');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (553,'Nixon');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (555,'Boss');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (556,'Bushnell');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (559,'Le Corone');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (558,'Fabulaetrusca');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (560,'Evanueva');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (561,'Ellebj');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (562,'Mini');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (563,'Vanto Gioielli');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (564,'Maria e Luisa Jewels');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (565,'goliard');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (566,'Grace96');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (567,'Ego Uomo');
INSERT INTO datafeed.Brand (`_id`, name) VALUES (568,'Le Favole');