alter table `Brand_Rule` drop foreign key `FK1sf9yib73cvy6oyr44yubf3rr`;
alter table `Brand_Rule` drop foreign key `FK2kb4pvyk0dyyr42bfugaciohs`;
alter table `DataFeed` drop foreign key `FKcig5tra3c497bh1ttje7r8kug`;
alter table `Product` drop foreign key `FK48a1i0xbkt3jcx02o85nu9dkc`;
alter table `Product` drop foreign key `FKhtc18ub0r1c7wqmaguu3gqvv3`;
alter table `Product` drop foreign key `FKr76o3pvayty43nlwy314xb75y`;
alter table `Product_CustomAttribute` drop foreign key `FKm1xcjkp1itar8hpb8kv4r04d3`;
alter table `Product_CustomAttribute` drop foreign key `FKmq7xaqvovsvnr132ucq4bed9j`;
alter table `Product_ImageLink` drop foreign key `FK8ol8t3slcrwlsvtcff7jxab84`;
alter table `Product_ImageLink` drop foreign key `FKh2tq5bb74bb67uokj7xau6gr8`;
alter table `Product_Output` drop foreign key `FKoirkyutsaudpuja4uiv44a5aa`;
alter table `Product_Output` drop foreign key `FK4d67cgx619vyroqksqu8epso4`;
alter table `Root` drop foreign key `FKrpktp3u2xvh86dxhq3rljvcjo`;
alter table `Root_Product` drop foreign key `FK5x76f7vxqpre0liuulr9fstce`;
alter table `Root_Product` drop foreign key `FKpmjl2f3s57vik0yq6hy385f2q`;
drop table if exists `AmazonFeedSubmission`;
drop table if exists `Author`;
drop table if exists `Brand`;
drop table if exists `Brand_Rule`;
drop table if exists `Category`;
drop table if exists `CustomAttribute`;
drop table if exists `DataFeed`;
drop table if exists `ImageLink`;
drop table if exists `Output`;
drop table if exists `Price`;
drop table if exists `Product`;
drop table if exists `Product_CustomAttribute`;
drop table if exists `Product_ImageLink`;
drop table if exists `Product_Output`;
drop table if exists `Root`;
drop table if exists `Root_Product`;
drop table if exists `Rule`;
